messages:

  prefix: "&d&lEAuctions &8» "

  no-permission: "&cYou don't have permission."

  invalid-price: "&cInvalid price."

  invalid-item: "&cHold an item in your hand."

  reload: "&aConfiguration reloaded."

  sold: "&aYour item has been listed for &f%price%&a."

auction:

  currency-symbol: "$"

  max-price: 1000000000000

  min-price: 1

# =========================================================
# PURCHASE CONFIRMATION
# =========================================================

language: en

# true  = confirmation appears
# false = direct purchase

purchase-confirmation: true
