name: EAuctions
version: 1.0.0
main: com.elyther.eauctions.EAuctions
api-version: '1.21'

author: Elyther
description: A modern Vault-supported Auction House plugin.

depend:
  - Vault

commands:

  ah:
    description: Open the Auction House
    usage: /ah [item|sell|reload|toggle]
    aliases:
      - auction
      - auctions

permissions:

  eauctions.use:
    description: Use Auction House
    default: true

  eauctions.sell:
    description: Sell items on Auction House
    default: true

  eauctions.reload:
    description: Reload EAuctions
    default: op
